# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c301049aa7f02ad655eb45e7028096cb44f7562e97430b085a225f86834cda1ee1e3cfde81fa75dc90e9a9413628345f159a0a1a20924253e826f1c3d552433c
  private_key_password: "Ax1p90Fbe4"
  twilio_sid_dev: "ACf04fc05763bd37135f151acc411246c2"
  twilio_token_dev: "d438d79c9fdb2745bf42186348432c34"

  braintree_environment: :sandbox
  braintree_merchant_id: "h4c4ny7qv7rsfcwy"
  braintree_public_key: "zqnk6yd49ns8j452"
  braintree_private_key: "bbc20d8ec239fdd90fa72e824b0dffcc"

test:
  secret_key_base: bd675c3dd81ffab20d5ae3900fbaf05453d8b28dba557cd6cff85361db4a0d3076a0455765876045aa500526af5e072b6773a84ea8935ff8d9b0b2c7105ea94a
  private_key_password: <%= ENV["PRIVATE_KEY_PASSWORD"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  private_key_password: <%= ENV["PRIVATE_KEY_PASSWORD"] %>
  twilio_sid: <%= ENV["TWILIO_SID"] %>
  twilio_token: <%= ENV["TWILIO_TOKEN"] %>
  twilio_sid_dev: <%= ENV["TWILIO_SID_DEV"] %>
  twilio_token_dev: <%= ENV["TWILIO_TOKEN_DEV"] %>

  braintree_environment: :production
  braintree_merchant_id: <%= ENV["BRAINTREE_MERCHANT_ID"] %>
  braintree_public_key: <%= ENV["BRAINTREE_PUBLIC_KEY"] %>
  braintree_private_key: <%= ENV["BRAINTREE_PRIVATE_KEY"] %>